### ISSUE TITLE
this plugin is not working

### ISSUE THREAD

**Issue by dextherry** [MattieBelt/strapi-provider-email-gmail-2lo#1]
Hi, I installed this plugin, but it not appears in the providers options, 

![image](https://user-images.githubusercontent.com/1903077/73023095-cbe22280-3df8-11ea-9337-7d80f3b1f1ed.png)

how can I get it working?
I am using strapi 3.0.0-beta.18.4
Regards

**Comment by MattieBelt** [comment]
Hi @dextherry I have update the provider to Strapi stable standards. It works with a strapi v3.0.x project.

**Comment by MattieBelt** [comment]
Email provider configuration by GUI is removed in stable strapi, closing this issue
