### ISSUE TITLE
Configuration issue: errors sending email with Strapi 3.3.4

### ISSUE THREAD

**Issue by lucap84** [MattieBelt/strapi-provider-email-gmail-2lo#3]
I followed the [described setup steps](https://github.com/MattieBelt/strapi-provider-email-gmail-2lo/blob/master/README.md) but I found some errors on email sending and the email are not sent (see at the end for the error logs)

**It could be useful to have a more detailed setup steps about Gmail/OAuth configuration**.
This is my situation:

1. "Gmail API" enabled for my project
2. "Oauth consent screen" configured as:
Publication Status: "Test in progress" (not "Production")
User type: "External"
Users added: my personal gmail address and also the gmail address of the account I'm configuring GoogleCloudPlatform
3. Service Account configured as:
Enabled
Email something like this: `"service-account-name@project-xxx.iam.gserviceaccount.com"`
Enable delegation across the G Suite domain: checked
4. Created a new Private key for your service account
Private JSON key active and downloaded in my local machine
5. Created file `/config/plugins.js` following the provided example.
Provider options
```
module.exports = ({ env }) => ({
  // ...
  email: {
    provider: 'gmail-2lo',
    providerOptions: {
      username: // <-- here which email should I use?
      clientId: // <-- here I put the "client_id" value of my private JSON key
      privateKey: // <-- here I put the "private_key" value of my private JSON key
    },
    settings: {
      defaultFrom: 'myemail@example.com',
      defaultReplyTo: 'myemail@example.com',
    },
  },
  // ...
});
```

**Error logs:**
1. Using `providerOptions.username` with Service Account email (like `"service-account-name@project-xxx.iam.gserviceaccount.com"`):
```
Error: invalid_request: Principal must be an email address
[{"messages":[{"id":"Auth.form.error.email.invalid"},{"mailer_error":"invalid_request: Principal must be an email address"}]}]
```
2. Using `providerOptions.username` with one of the users added in Oauth consent screen:
```
Error: unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.
[{"messages":[{"id":"Auth.form.error.email.invalid"},{"mailer_error":"unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested."}]}]
```

**What I missed? Can you please help me to correctly configure it?**

Strapi version: ` 3.3.4 (node v12.18.4)`

**Comment by josemanuelguzman** [comment]
I have the same issue!

**Comment by MattieBelt** [comment]
Hey @lucap84,

Thanks for trying out the provider and waiting for my response, had some busy days (moved houses and had holidays).
Regarding your first point: the `providerOptions.username` indeed needs to be an existing email address within your domain/project and not the service-account email. 

Are you looking for a "three-legged OAuth", then you should use [this provider](https://github.com/alexandre-lavoie/strapi-provider-email-gmail-oauth2) or [a fork](https://github.com/alexandre-lavoie/strapi-provider-email-gmail-oauth2/network/members) of it. 
Or do you make use of Google Workspace (prev. G suite), then you need to follow some extra steps: https://github.com/MattieBelt/strapi-provider-email-gmail-2lo/blob/master/README.md#g-suite, following those steps when having G workspace should solve your second error. If this is not the case feel free to let me know.

@josemanuelguzman Are you also use Google Workspace, if so please follow the linked steps from the Readme.

**Comment by MattieBelt** [comment]
I hoped this worked for you guys. 

Closing this, let me know if you still run into this problem.
