### ISSUE TITLE
Error: Can't generate token. Check your auth options

### ISSUE THREAD

**Issue by cipiasentini** [MattieBelt/strapi-provider-email-gmail-2lo#4]
Any idea why I am getting this `[2021-07-19T22:15:46.009Z] error Error while sending email: Error: Can't generate token. Check your auth options` error when trying to send an email? 
The full error logs are:
```
[
  {
     messages: [
      { id: 'Auth.form.error.email.invalid' },
       { mailer_error: "Can't generate token. Check your auth options" }
     ]
   }
]
```

On my local machine it worked just fine, but when I changed to my production machine (iit has the same env variables) shows this issue.

My plugin config:

```
module.exports = ({ env }) => ({
  email: {
    provider: 'gmail-2lo',
    providerOptions: {
      username: env('EMAIL_USERNAME'),
      clientId: env('EMAIL_CLIENT_ID'),
      privateKey: env('EMAIL_PRIVATE_KEY').replace(/\\n/g, '\n'),
    },    
    settings: {
      defaultFrom: 'xxx@xxx.xxx',
      defaultReplyTo: xxx@xxx.xxx',
    },
  },
});
```

**Comment by cipiasentini** [comment]
Found out the issue. It was the quotes from the .env file variables. If you load from an env file the variables please don't use double quotes

**Comment by FoolishAgency** [comment]
This was extremely helpful! Thanks, you saved me a lot of time!
